### ISSUE TITLE
QR CODE DOWLAND

### ISSUE THREAD

**Issue by YunusEmreGok** [nguyenary/nguyenary#1]
Hi , CR CODE DOWLAND CODE ?

**Comment by YunusEmreGok** [comment]
.PNG

**Comment by nguyenary** [comment]
@YunusEmreGok Hi, to download the image file please set the file path to be saved in the create() function. You will receive a file on the server that runs the code with the specified path
![image](https://user-images.githubusercontent.com/7163751/133914102-bf707fab-493b-4f0f-91e2-151c8cb54bb2.png)

**Comment by YunusEmreGok** [comment]
Can you help if the code is not working ? And how to download the file with the api ?

**Comment by nguyenary** [comment]
What are you having problems with?
As mentioned above you have 2 options: get the image path or save the file on the server. Please see `example.php` to understand more.

**Comment by YunusEmreGok** [comment]
Code : 
require_once 'vendor/autoload.php';

use nguyenary\QRCodeMonkey\QRCode;

$qrcode = new QRCode('test');

$qrcode->setConfig([

]);

print_r($qrcode->create());

$qrcode->create('nguyen.png');

exit();


Demo : https://yunusemregok.com.tr/gappze/qr.php

**Comment by nguyenary** [comment]
You are calling create() 2 times

```php
print_r($qrcode->create());

// And

$qrcode->create('nguyen.png');
```

File has been create at here when calling `$qrcode->create('nguyen.png');`

See here: https://yunusemregok.com.tr/gappze/nguyen.png

**Comment by YunusEmreGok** [comment]
pdf , jpeg dowland ?
is it possible that you want to download a pre-generated qr code ?

**Comment by nguyenary** [comment]
![image](https://user-images.githubusercontent.com/7163751/133919542-fab0af97-fb2a-4f02-abfd-4a4266c7edd4.png)
Call `$qrcode->setFileType('pdf');` before calling the `creat()` function

**Comment by YunusEmreGok** [comment]
$qrcode->setFileType('pdf');
$qrcode->create(  'test.pdf');


it's not working, so what's my mistake here ?

**Comment by YunusEmreGok** [comment]
$qrcode->setSize(100);

output 125x125 ?
Help
